### ISSUE TITLE
yum install php72u-yaml stopped working

### ISSUE THREAD

**Issue by Zodzie** [iusrepo/php72u-pecl-yaml#2]
for months our ansible script to install php72u-yaml among many other php72u packages worked with no problem.
But now I am trying to solve this configuration drift, where php72u-yaml stopped working for us, and php72u-pecl-yaml is the only option.

Please help us understand what changed

./epel.repo:enabled=1
./ius.repo:enabled = 1
./yarn.repo:enabled = 1
[root@openresty] yum.repos.d $ yum whatprovides php72u-yaml
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.trouble-free.net
 * epel: epel.mirror.constant.com
 * extras: mirror.cc.columbia.edu
 * updates: mirror.cc.columbia.edu
No matches found

[root@openresty] yum.repos.d $ yum whatprovides php72u-pecl-yaml
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.trouble-free.net
 * epel: fedora-epel.mirrors.tds.net
 * extras: mirror.cc.columbia.edu
 * updates: mirror.cc.columbia.edu
php72u-pecl-yaml-2.0.4-1.el7.ius.x86_64 : Support for YAML 1.1 serialization using the LibYAML library
Repo        : ius

**Comment by carlwgeorge** [comment]
Previously the spec file had a [virtual provides for php72u-yaml](https://github.com/iusrepo/php72u-pecl-yaml/blob/2.0.2-1/SPECS/php72u-pecl-yaml.spec#L35).  When I [updated the spec file for 2.0.4](https://github.com/iusrepo/php72u-pecl-yaml/commit/052b1dd4422f7b15c0f9d283e8721dc830ddf6a7), I merged it with the Fedora spec file, which did not have those lines.

The correct option would be to use the actual package name of php72u-pecl-yaml and not rely on a virtual provides.  But if you'd like to add it back to the spec file, I'd be happy to review a pull request.  It is [Hacktoberfest](https://hacktoberfest.digitalocean.com) after all.

**Comment by Zodzie** [comment]
Thanks for the quick response and info on Hacktoberfest! 
It doesn't seem like I have ability to create a branch here. 
`php72u-pecl-yaml ryan.rosado$ git push origin hacktoberfest-iusrepo-php72u-yaml
remote: Permission to iusrepo/php72u-pecl-yaml.git denied to Zodzie.`

any advice?

**Comment by Zodzie** [comment]
oh! looks like I may need to fork first. trying now

**Comment by Zodzie** [comment]
https://github.com/iusrepo/php72u-pecl-yaml/pull/3

**Comment by carlwgeorge** [comment]
Closing this in favor of #3.
